server:
  version:
  port:
postgresql:
  url:
s3:
  region:
  accessKeyId:
  secretAccessKey:
  bucket:
  domain:
discord:
  bot:
    name:
    client-id:
    token:
    owner-id:
  server:
    id:
  guild:
    id:
namespace:
  discord:
  guild:
document:
  title:
  description:
  version:
  path:
logger:
  path:
  filename:
  pretty:
  level:
  stdout:
