server:
  version:
  port:
postgresql:
  url:
discord:
  bot:
    name:
    client-id:
    token:
    owner-id:
  server:
    id:
  guild:
    id:
document:
  title:
  description:
  version:
  path:
logger:
  path:
  filename:
  pretty:
  level:
  stdout:
