server:
  version:
  port:
postgresql:
  url:
aws:
  s3:
    region:
    accessKeyId:
    secretAccessKey:
    bucket:
    domain:
discord:
  webhookURL:
    kakaoLink:
    kakaoError:
    kakaoComplete:
  bot:
    name:
    clientId:
    token:
    ownerId:
    iconURL:
  servers:
    - name:
      slug:
      id:
      market:
        wts:
          channels:
            - id:
              name:
        wtb:
          channels:
            - id:
              name:
        wtt:
          channels:
            - id:
              name:
        allowedRoleIds:
        disallowedRoleIds:
      auction:
        channels:
          - id:
            name:
        allowedRoleIds:
        disallowedRoleIds:
      thread:
        channels:
          - id:
            name:
            categorySource:
        allowedRoleIds:
        disallowedRoleIds:
      command:
        channels:
          - id:
            name:
            allowedRoleIds:
            disallowedRoleIds:
namespace:
  discord:
  group:
document:
  title:
  description:
  version:
  path:
logger:
  path:
  filename:
  pretty:
  level:
  stdout:
