server:
  version:
  port:
postgresql:
  url:
s3:
  region:
  accessKeyId:
  secretAccessKey:
  bucket:
  domain:
discord:
  bot:
    name:
    client-id:
    token:
    owner-id:
  server:
    id:
    market:
      wts:
        channels:
          커스텀:
          기성품:
          키캡:
          아티산:
          기타:
      wtb:
        channels:
          커스텀:
          기성품:
          키캡:
          아티산:
          기타:
      wtt:
        channels:
          커스텀:
          기성품:
          키캡:
          아티산:
          기타:
      allowed-role-ids:
      disallowed-role-ids:
    auction:
      channels:
        경매 일정:
        경매:
      allowed-role-ids:
      disallowed-role-ids:
    community:
      channels:
        사진 영상:
        정보 후기:
        거래 후기:
      allowed-role-ids:
      disallowed-role-ids:
namespace:
  discord:
  guild:
document:
  title:
  description:
  version:
  path:
logger:
  path:
  filename:
  pretty:
  level:
  stdout:
