version: "3.8"
services:
  api:
    build:
      dockerfile: ./apps/api/Dockerfile
      context: .
    ports:
      - "8080:8080"
  bot:
    build:
      dockerfile: ./apps/bot/Dockerfile
      context: .
    ports:
      - "3000:3000"
