server:
  version:
  port:
  cors:
    origins:
frontend:
  host:
  port:
oauth2:
  discord:
    clientId:
    clientSecret:
    callbackURL:
  naver:
    clientId:
    clientSecret:
    callbackURL:
  kakao:
    clientId:
    clientSecret:
    callbackURL:
jwt:
  access:
    domain:
    secret:
    expiresIn:
  refresh:
    domain:
    secret:
    expiresIn:
postgresql:
  url:
redis:
  host:
  port:
aws:
  accountId:
  s3:
    region:
    accessKeyId:
    secretAccessKey:
    bucket:
    domain:
  lambda:
    region:
    accessKeyId:
    secretAccessKey:
  eventBridge:
    region:
    accessKeyId:
    secretAccessKey:
document:
  title:
  description:
  version:
  path:
logger:
  path:
  filename:
  pretty:
  level:
  stdout:
discord:
  webhookURL:
    offer:
    userReview:
    auction:
    report:
