server:
  version:
  port:
postgresql:
  url:
redis:
  host:
  port:
s3:
  region:
  accessKeyId:
  secretAccessKey:
  bucket:
  domain:
document:
  title:
  description:
  version:
  path:
logger:
  path:
  filename:
  pretty:
  level:
  stdout:
discord:
  bot:
    token:
