server:
  version:
  port:
oauth2:
  discord:
    clientId:
    clientSecret:
    callbackURL:
  naver:
    clientId:
    clientSecret:
    callbackURL:
jwt:
  access:
    secret:
    expiresIn:
  refresh:
    secret:
    expiresIn:
postgresql:
  url:
redis:
  host:
  port:
s3:
  region:
  accessKeyId:
  secretAccessKey:
  bucket:
  domain:
document:
  title:
  description:
  version:
  path:
logger:
  path:
  filename:
  pretty:
  level:
  stdout:
discord:
  bot:
    token:
