export enum OfferErrorMessage {
  OFFER_IS_NOT_FOUND = 'Offer is not found',
  OFFER_FROM_REPORTED_NOT_FOUND = 'Offer from reported not found',
  OFFER_CREATION_FAILED = 'Offer creation failed',
  OFFER_CHANGES_FROM_INCOMPATIBLE_PLATFORMS = 'Offer changes from incompatible platforms',
  OFFER_CHANGES_FROM_UNAUTHORIZED_USER = 'Offer changes from unauthorized user',
  OFFER_DELETE_COMMAND_FROM_UNAUTHORIZED_USER = 'Offer delete command from unauthorized user',
  OFFER_BUMP_STUCK_ON_COOLDOWN = 'Offer bump stuck on cooldown',
  OFFER_REPORT_NOT_FOUND = 'Offer report not found',
  COMMENT_OFFER_REPORT_REQUEST_FROM_NON_SELLER = 'Comment offer report request from non seller',
  UNCOMMENTED_REPORT_EXISTS = 'Uncommented report exists',
  FIND_REQUEST_FROM_UNAUTHORIZED_USER = 'Find request from unauthorized user',
  CREATE_REQUEST_FROM_UNAUTHORIZED_USER = 'Create request from unauthorized user',
  DAILY_OFFER_POSTING_LIMIT_EXCEEDED = 'Daily offer posting limit exceeded',
}
